/**
 * Read-only access to the Mumble server via Ice (ADR-0002, analysis 3.2).
 * Only methods the read secret allows. There are no writing calls here.
 */
import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import type { Channel, User } from "@ruumble/protocol";

export interface Basics {
  channels: Channel[];
  users: (User & { address: string })[];
  /** seconds since the virtual server started; decreases → restart */
  uptime: number;
}

export interface ServerInfo {
  name: string;
  version: string;
}

/** Everything the service reads from the Mumble server. */
export interface MumbleSource {
  basics(): Promise<Basics>;
  serverInfo(): Promise<ServerInfo>;
  listeners(channelIds: number[]): Promise<Record<string, number[]>>;
  canEnter(session: number, channelIds: number[]): Promise<Record<string, boolean>>;
  /** write permission (PermissionWrite) on a channel, e.g. for deleting other people's board posts (ADR-0011) */
  canWrite(session: number, channelId: number): Promise<boolean>;
  /** SHA1 hex of certs[0], `null` without a certificate or for an unknown session */
  certHash(session: number): Promise<string | null>;
  /** avatar image of a registered user (Ice getTexture), `null` without an image (AP9) */
  texture(userId: number): Promise<Uint8Array | null>;
  close(): Promise<void>;
}

export interface IceOptions {
  host: string;
  port: number;
  secret: string;
  /** if omitted: first running server (in 1.6.870 it has ID 0, S1) */
  serverId?: number;
}

const require = createRequire(import.meta.url);

/** 16-byte address from Ice as text; IPv4 in IPv6 (::ffff:a.b.c.d) becomes a.b.c.d. */
export function formatAddress(bytes: Uint8Array | number[] | null | undefined): string {
  const b = Array.from(bytes ?? []);
  if (b.length !== 16) return "";
  if (b.slice(0, 10).every((x) => x === 0) && b[10] === 0xff && b[11] === 0xff) return b.slice(12).join(".");
  const groups: string[] = [];
  for (let i = 0; i < 16; i += 2) groups.push(((b[i]! << 8) | b[i + 1]!).toString(16));
  return groups.join(":");
}

export class IceMumbleSource implements MumbleSource {
  private readonly communicator: { destroy(): Promise<void> };
  // Ice proxies are untyped (generated by slice2js)
  private readonly meta: any;
  private readonly server: any;
  private readonly permissionEnter: number;
  private readonly permissionWrite: number;

  private constructor(communicator: { destroy(): Promise<void> }, meta: any, server: any, permissions: { enter: number; write: number }) {
    this.communicator = communicator;
    this.meta = meta;
    this.server = server;
    this.permissionEnter = permissions.enter;
    this.permissionWrite = permissions.write;
  }

  static async connect(opts: IceOptions): Promise<IceMumbleSource> {
    const { Ice } = require("ice");
    const { MumbleServer } = require("../gen/MumbleServer.cjs");
    const init = new Ice.InitializationData();
    init.properties = Ice.createProperties();
    init.properties.setProperty("Ice.ImplicitContext", "Shared");
    init.properties.setProperty("Ice.Default.EncodingVersion", "1.0");
    init.properties.setProperty("Ice.Default.InvocationTimeout", "5000");
    const communicator = Ice.initialize(init);
    communicator.getImplicitContext().put("secret", opts.secret);
    try {
      const endpoint = `tcp -h ${opts.host} -p ${opts.port}`;
      const meta = await MumbleServer.MetaPrx.checkedCast(communicator.stringToProxy(`Meta:${endpoint}`));
      // up to Mumble 1.4 the interface was called "Murmur": then there is no MumbleServer::Meta
      if (!meta) throw new Error(`No MumbleServer Meta object at ${endpoint}. Ruumble needs Mumble server 1.5 or later (up to 1.4 the Ice interface was called "Murmur").`);
      let id = opts.serverId;
      if (id === undefined) {
        const booted = await meta.getBootedServers();
        if (booted.length === 0) throw new Error("Kein laufender virtueller Server");
        // The proxy carries the endpoint as seen by the server (e.g. container IP): take over only the identity (S1)
        id = Number(booted[0].ice_getIdentity().name);
      }
      const server = MumbleServer.ServerPrx.uncheckedCast(communicator.stringToProxy(`s/${id}:${endpoint}`));
      return new IceMumbleSource(communicator, meta, server, { enter: MumbleServer.PermissionEnter, write: MumbleServer.PermissionWrite });
    } catch (e) {
      await communicator.destroy();
      throw e;
    }
  }

  async basics(): Promise<Basics> {
    const [channels, users, uptime] = await Promise.all([this.server.getChannels(), this.server.getUsers(), this.server.getUptime()]);
    return {
      channels: [...channels.values()].map((c: any) => ({
        id: c.id,
        parent: c.parent < 0 ? null : c.parent,
        name: c.name,
        position: c.position,
        links: [...c.links],
        temporary: c.temporary,
      })),
      users: [...users.values()].map((u: any) => ({
        session: u.session,
        name: u.name,
        channel: u.channel,
        selfMute: u.selfMute,
        selfDeaf: u.selfDeaf,
        mute: u.mute,
        deaf: u.deaf,
        suppress: u.suppress,
        userId: u.userid >= 0 ? u.userid : null,
        avatar: null, // set by the hub from the avatar cache
        idleMinutes: Math.max(0, Math.floor(u.idlesecs / 60)), // whole minutes: snapshot changes at most once a minute
        recording: u.recording,
        address: formatAddress(u.address),
      })),
      uptime,
    };
  }

  async serverInfo(): Promise<ServerInfo> {
    const [conf, defaults, version] = await Promise.all([
      this.server.getConf("registername").catch(() => ""),
      this.meta.getDefaultConf().catch(() => new Map()),
      this.meta.getVersion(),
    ]);
    // like the Mumble client: registername, otherwise "Root" (analysis 3.2)
    const name = conf || defaults.get("registername") || "Root";
    return { name, version: `${version[0]}.${version[1]}.${version[2]}` };
  }

  async listeners(channelIds: number[]): Promise<Record<string, number[]>> {
    const lists = await Promise.all(channelIds.map((id) => this.server.getListeningUsers(id).catch(() => [])));
    const result: Record<string, number[]> = {};
    channelIds.forEach((id, i) => {
      if (lists[i].length > 0) result[String(id)] = [...lists[i]];
    });
    return result;
  }

  async canEnter(session: number, channelIds: number[]): Promise<Record<string, boolean>> {
    const perms = await Promise.all(channelIds.map((id) => this.server.hasPermission(session, id, this.permissionEnter).catch(() => true)));
    const result: Record<string, boolean> = {};
    channelIds.forEach((id, i) => {
      if (!perms[i]) result[String(id)] = false; // a missing channel means true (protocol)
    });
    return result;
  }

  async canWrite(session: number, channelId: number): Promise<boolean> {
    return this.server.hasPermission(session, channelId, this.permissionWrite).catch(() => false);
  }

  async certHash(session: number): Promise<string | null> {
    try {
      const certs = await this.server.getCertificateList(session);
      if (!certs.length) return null;
      return createHash("sha1").update(Buffer.from(certs[0])).digest("hex");
    } catch {
      return null;
    }
  }

  async texture(userId: number): Promise<Uint8Array | null> {
    try {
      const tex = await this.server.getTexture(userId);
      return tex && tex.length > 0 ? Uint8Array.from(tex) : null;
    } catch {
      return null;
    }
  }

  async close(): Promise<void> {
    await this.communicator.destroy();
  }
}
