<script lang="ts">
  import { parseTaskList, type Post } from "@ruumble/protocol";
  import { renderInline, renderMarkdown } from "../../board/render.ts";
  import AttachmentView from "./AttachmentView.svelte";
  import CodeBlock from "./CodeBlock.svelte";

  /** `numbers`: line numbers for code (only in the popup, not in the preview on the card) */
  /** `large`: larger image (in the popup) */
  /** `ontoggle`: tick a task of a task list (A2); without it the checkboxes are read-only */
  let { post, numbers = false, large = false, ontoggle }: { post: Post; numbers?: boolean; large?: boolean; ontoggle?: (index: number, done: boolean) => void } = $props();
  const tasks = $derived(post.kind === "text" ? parseTaskList(post.text) : null);
  // images and files: the text is the caption, also Markdown; task lists: only the introduction
  const html = $derived(post.kind === "code" ? "" : tasks ? (tasks.intro ? renderMarkdown(tasks.intro) : "") : post.text.trim() ? renderMarkdown(post.text) : "");
</script>

{#if post.kind === "code"}
  <CodeBlock code={post.text} language={post.language} {numbers} />
{:else if tasks}
  {#if html}<div class="md">{@html html}</div>{/if}
  <ul class="tasks">
    {#each tasks.tasks as task (task.line)}
      <li class:done={task.done}>
        <label>
          <!-- no optimistic update (ADR-0003): back to the known state, the box changes with the service's answer -->
          <input type="checkbox" checked={task.done} disabled={!ontoggle} onchange={(e) => { e.currentTarget.checked = task.done; ontoggle?.(task.index, !task.done); }} />
          <span class="md">{@html renderInline(task.text)}</span>
        </label>
      </li>
    {/each}
  </ul>
{:else if post.kind === "text"}
  <!-- generated by markdown-it (without HTML) and sanitised with DOMPurify (render.ts) -->
  <div class="md">{@html html}</div>
{:else if post.attachment}
  <AttachmentView {post} {large} />
  {#if html}<div class="md caption">{@html html}</div>{/if}
{/if}

<style>
  .md { font-size: 14px; line-height: 1.5; overflow-wrap: anywhere; }
  .caption { margin-top: 8px; }
  .tasks { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 2px; }
  .tasks label { display: flex; align-items: flex-start; gap: 8px; min-height: 28px; padding: 2px 0; cursor: pointer; }
  .tasks input { width: 16px; height: 16px; margin: 3px 0 0; accent-color: var(--color-navy); flex-shrink: 0; cursor: pointer; }
  .tasks input:disabled { cursor: default; }
  .tasks .done .md { text-decoration: line-through; color: var(--color-blue-700); }
  .md :global(p) { margin: 0 0 6px; }
  .md :global(h1), .md :global(h2), .md :global(h3) { font-size: 15px; margin: 4px 0 6px; }
  .md :global(ul), .md :global(ol) { margin: 0 0 6px; padding-left: 20px; }
  .md :global(a) { color: var(--color-blue-500); }
  .md :global(code) { background: var(--color-surface); padding: 0 3px; border-radius: 3px; font-size: 13px; }
  .md :global(pre) { background: var(--color-surface); padding: 8px; border-radius: var(--radius-md); overflow-x: auto; font-size: 12.5px; }
  .md :global(table) { border-collapse: collapse; font-size: 13px; }
  .md :global(th), .md :global(td) { border: 1px solid var(--color-blue-300); padding: 2px 6px; }
  .md :global(blockquote) { margin: 0 0 6px; padding-left: 8px; border-left: 3px solid var(--color-blue-300); color: var(--color-blue-700); }
</style>
